version: '3.9'

services:
  cypress:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 80:8080
    volumes:
      - .:/app/
    command: npx http-server ./mochawesome-report/
